;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Parkour.Action.Jump.Plyos",DevComment="")
+GameplayTagList=(Tag="Parkour.Action.Jump.Strides",DevComment="")
+GameplayTagList=(Tag="Parkour.Action.Landing.Default",DevComment="")
+GameplayTagList=(Tag="Parkour.Action.Landing.Precision",DevComment="")
+GameplayTagList=(Tag="Parkour.Action.Landing.Roll",DevComment="")
+GameplayTagList=(Tag="Parkour.Action.Vault.Kong",DevComment="")
+GameplayTagList=(Tag="Parkour.Action.Vault.Lazy",DevComment="")
+GameplayTagList=(Tag="Parkour.Surface.Backend.Cliff",DevComment="")
+GameplayTagList=(Tag="Parkour.Surface.Backend.Downhill",DevComment="")
+GameplayTagList=(Tag="Parkour.Surface.Backend.Horizontal",DevComment="")
+GameplayTagList=(Tag="Parkour.Surface.Backend.Uphill",DevComment="")
+GameplayTagList=(Tag="Parkour.Surface.Gap.Between",DevComment="")
+GameplayTagList=(Tag="Parkour.Surface.Gap.Full",DevComment="")
+GameplayTagList=(Tag="Parkour.Surface.Gap.Under",DevComment="")
+GameplayTagList=(Tag="Parkour.Surface.Height.Chest",DevComment="")
+GameplayTagList=(Tag="Parkour.Surface.Height.Face",DevComment="")
+GameplayTagList=(Tag="Parkour.Surface.Height.Knee",DevComment="")
+GameplayTagList=(Tag="Parkour.Surface.Height.Waist",DevComment="")
+GameplayTagList=(Tag="Parkour.Surface.Type.Bar",DevComment="")
+GameplayTagList=(Tag="Parkour.Surface.Type.Box",DevComment="")
+GameplayTagList=(Tag="Parkour.Surface.Type.Ledge",DevComment="")
+GameplayTagList=(Tag="Parkour.Surface.Type.Wall",DevComment="")
+GameplayTagList=(Tag="Parkour.Surface.Width.Narrow",DevComment="")
+GameplayTagList=(Tag="Parkour.Surface.Width.Thin",DevComment="")
+GameplayTagList=(Tag="Parkour.Surface.Width.Wide",DevComment="")

