;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Action.Movement.AirDash",DevComment="")
+GameplayTagList=(Tag="Action.Movement.Dash",DevComment="")
+GameplayTagList=(Tag="Action.Movement.Jump",DevComment="")
+GameplayTagList=(Tag="Action.Parkour.LetGo",DevComment="")
+GameplayTagList=(Tag="Action.Parkour.Mantle",DevComment="")
+GameplayTagList=(Tag="Action.Parkour.QuickTurn",DevComment="")
+GameplayTagList=(Tag="Action.Parkour.Roll",DevComment="")
+GameplayTagList=(Tag="Action.Parkour.Underbar",DevComment="")
+GameplayTagList=(Tag="Action.Parkour.Vault.Dash",DevComment="")
+GameplayTagList=(Tag="Action.Parkour.Vault.Enemy",DevComment="")
+GameplayTagList=(Tag="Action.Parkour.Vault.Kong",DevComment="")
+GameplayTagList=(Tag="Action.Parkour.Vault.Safety",DevComment="")
+GameplayTagList=(Tag="Action.Parkour.Vault.Speed",DevComment="")
+GameplayTagList=(Tag="Action.Parkour.WallEject",DevComment="")
+GameplayTagList=(Tag="State.Balance.TightRope",DevComment="")
+GameplayTagList=(Tag="State.Movement.Airbone",DevComment="")
+GameplayTagList=(Tag="State.Movement.Falling",DevComment="")
+GameplayTagList=(Tag="State.Movement.Grounded",DevComment="")
+GameplayTagList=(Tag="State.Movement.Wall",DevComment="")
+GameplayTagList=(Tag="State.Parkour.Climb",DevComment="")
+GameplayTagList=(Tag="State.Parkour.Hang",DevComment="")
+GameplayTagList=(Tag="State.Parkour.Hang.Rope",DevComment="")
+GameplayTagList=(Tag="State.Parkour.Hang.Rope.Swing",DevComment="")
+GameplayTagList=(Tag="State.Parkour.Hang.Shimmy",DevComment="")
+GameplayTagList=(Tag="State.Parkour.WallRunning",DevComment="")
+GameplayTagList=(Tag="State.Parkour.WallRunning.Left",DevComment="")
+GameplayTagList=(Tag="State.Parkour.WallRunning.Right",DevComment="")
+GameplayTagList=(Tag="State.Parkour.WallSlides",DevComment="")
+GameplayTagList=(Tag="State.Status.Crouch",DevComment="")
+GameplayTagList=(Tag="State.Status.Sliding",DevComment="")
+GameplayTagList=(Tag="State.Status.Sprinting",DevComment="")

