;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Parkour.Action.Vault.Lazy",NewTagName="Parkour.Action.Vault.Safety")
+GameplayTagList=(Tag="Obstacle.Bar.Between",DevComment="")
+GameplayTagList=(Tag="Obstacle.Bar.Under",DevComment="")
+GameplayTagList=(Tag="Obstacle.Detect.None",DevComment="")
+GameplayTagList=(Tag="Obstacle.Detect.Obstacle",DevComment="")
+GameplayTagList=(Tag="Obstacle.Height.Chest",DevComment="")
+GameplayTagList=(Tag="Obstacle.Height.Knee",DevComment="")
+GameplayTagList=(Tag="Obstacle.Height.OverHigh",DevComment="")
+GameplayTagList=(Tag="Obstacle.Height.Waist",DevComment="")
+GameplayTagList=(Tag="Obstacle.Pass.Blocked",DevComment="")
+GameplayTagList=(Tag="Obstacle.Pass.Clear",DevComment="")
+GameplayTagList=(Tag="Obstacle.Surface.Abyss",DevComment="")
+GameplayTagList=(Tag="Obstacle.Surface.Deep",DevComment="")
+GameplayTagList=(Tag="Obstacle.Surface.Even",DevComment="")
+GameplayTagList=(Tag="Obstacle.Surface.Low",DevComment="")
+GameplayTagList=(Tag="Parkour.Jump.Building.Extreme",DevComment="")
+GameplayTagList=(Tag="Parkour.Jump.Building.High",DevComment="")
+GameplayTagList=(Tag="Parkour.Jump.Building.Short",DevComment="")
+GameplayTagList=(Tag="Parkour.Jump.Building.Wide",DevComment="")
+GameplayTagList=(Tag="Parkour.Jump.Hurdle",DevComment="")
+GameplayTagList=(Tag="Parkour.Jump.Normal",DevComment="")
+GameplayTagList=(Tag="Parkour.Jump.Plyos",DevComment="")
+GameplayTagList=(Tag="Parkour.Jump.Strides",DevComment="")
+GameplayTagList=(Tag="Parkour.Landing.Landing",DevComment="")
+GameplayTagList=(Tag="Parkour.Landing.Precision",DevComment="")
+GameplayTagList=(Tag="Parkour.Landing.Roll",DevComment="")
+GameplayTagList=(Tag="Parkour.Mantle.Normal",DevComment="")
+GameplayTagList=(Tag="Parkour.Mantle.Slow",DevComment="")
+GameplayTagList=(Tag="Parkour.Vault.Kong",DevComment="")
+GameplayTagList=(Tag="Parkour.Vault.Safety",DevComment="")
+GameplayTagList=(Tag="Parkour.Wall.Drop",DevComment="")
+GameplayTagList=(Tag="Parkour.Wall.Hang",DevComment="")
+GameplayTagList=(Tag="Parkour.Wall.Pop",DevComment="")
+GameplayTagList=(Tag="Parkour.Wall.Run",DevComment="")
+GameplayTagList=(Tag="Parkour.Wall.Shimmy",DevComment="")
+GameplayTagList=(Tag="Parkour.Wall.TurnHang",DevComment="")
+GameplayTagList=(Tag="Surface.Gap.Building",DevComment="")
+GameplayTagList=(Tag="Surface.Gap.Building.Height.Extreme",DevComment="")
+GameplayTagList=(Tag="Surface.Gap.Building.Height.High",DevComment="")
+GameplayTagList=(Tag="Surface.Gap.Building.Width.Extreme",DevComment="")
+GameplayTagList=(Tag="Surface.Gap.Building.Width.Large",DevComment="")
+GameplayTagList=(Tag="Surface.Gap.Normal",DevComment="")
+GameplayTagList=(Tag="Surface.Gap.Wide",DevComment="")
+GameplayTagList=(Tag="Surface.Space.Narrow",DevComment="")
+GameplayTagList=(Tag="Surface.Space.Wide",DevComment="")

